name = "tomato-bot-protection"
account_id = "a89184ca041c043abe13d73293dcf408"
compatibility_date = "2023-03-28"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[env.production]
name = "tomato-bot-protection"
route = "tomato-restaurant.pages.dev/*"

# Environment variables
[vars]
API_KEY = "tomato-api-key-9c8b7a6d5e4f3g2h1i"

[[d1_databases]]
binding = "DB"
database_name = "tomato-db"
database_id = "tomato-db-id"