name = "tomato-bot-protection"
type = "javascript"
account_id = "a89184ca041c043abe13d73293dcf408"
workers_dev = true
compatibility_date = "2023-03-28"

[site]
bucket = "./dist"
entry-point = "cloudflare"

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
zone_id = "a89184ca041c043abe13d73293dcf408"
route = "tomato-restaurant.pages.dev/*"

[vars]
API_KEY = "tomato-api-key-9c8b7a6d5e4f3g2h1i"